---
name: supply-chain

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Display available env variables
        run: env
        
      - name: Test
        run: mvn --no-transfer-progress test

      - name: Build Image
        id: build
        uses: vmware-tanzu/build-image-action@v1-alpha
        with:
          # auth
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          namespace: dev
          # image config
          destination: gcr.io/ship-interfaces-dev/github-actions-poc
          env: |
            BP_JAVA_VERSION=17

      - name: Validate Output
        run: |
          if [ "${{ steps.build.outputs.name }}" == "" ]; then
            echo "::error::No output from previous step"
            exit 1
          fi

      - name: Scan Image
        uses: anchore/scan-action@v3
        with:
          image: "${{ steps.build.outputs.name }}"
          fail-build: false
